/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  agent: () => import("@/views/agent/index.vue"),
  building: () => import("@/views/building/index.vue"),
  catalog: () => import("@/views/catalog/index.vue"),
  globe: () => import("@/views/globe/index.vue"),
  knowledge: () => import("@/views/knowledge/index.vue"),
  planning: () => import("@/views/planning/index.vue"),
  river: () => import("@/views/river/index.vue"),
  screen: () => import("@/views/screen/index.vue"),
};
