/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'agent',
    path: '/agent',
    component: 'layout.base$view.agent',
    meta: {
      title: '智能体',
      order: 8,
      icon: 'mdi:robot'
    }
  },
  {
    name: 'catalog',
    path: '/catalog',
    component: 'layout.base$view.catalog',
    meta: {
      title: '数据目录',
      order: 3,
      icon: 'mdi:database'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: '地理环境知识库',
      order: 7,
      icon: 'mdi:book-open-variant'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'planning',
    path: '/planning',
    component: 'layout.base$view.planning',
    meta: {
      title: '机动路线规划',
      order: 6,
      icon: 'mdi:routes'
    }
  },
  {
    name: 'river',
    path: '/river',
    component: 'layout.base$view.river',
    meta: {
      title: '渡河保障方案',
      order: 5,
      icon: 'mdi:ferry'
    }
  },
  {
    name: 'screen',
    path: '/screen',
    component: 'layout.base$view.screen',
    meta: {
      title: '统计大屏',
      order: 1,
      icon: 'mdi:monitor-dashboard'
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: '系统管理',
      order: 9,
      icon: 'mdi:cog'
    },
    children: [
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: '用户管理',
          icon: 'mdi:account-group',
          order: 1
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: '角色管理',
          icon: 'mdi:shield-account',
          order: 2
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: '菜单管理',
          icon: 'mdi:menu-open',
          order: 3,
          hideInMenu: true
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: '日志管理',
          icon: 'mdi:file-document-multiple',
          order: 4
        }
      },
      {
        name: 'system_online',
        path: '/system/online',
        component: 'view.system_online',
        meta: {
          title: '在线用户',
          icon: 'mdi:account-clock',
          order: 5
        }
      }
    ]
  }
];
