/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'agent',
    path: '/agent',
    component: 'layout.base$view.agent',
    meta: {
      title: 'AI Agent',
      order: 8,
      icon: 'mdi:robot'
    }
  },
  {
    name: 'building',
    path: '/building',
    component: 'layout.base$view.building',
    meta: {
      title: '楼宇夺控',
      order: 4,
      icon: 'mdi:office-building'
    }
  },
  {
    name: 'catalog',
    path: '/catalog',
    component: 'layout.base$view.catalog',
    meta: {
      title: '数据目录',
      order: 3,
      icon: 'mdi:database'
    }
  },
  {
    name: 'globe',
    path: '/globe',
    component: 'layout.base$view.globe',
    meta: {
      title: 'Web球',
      order: 2,
      icon: 'mdi:earth',
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: '知识库',
      order: 7,
      icon: 'mdi:book-open-variant'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'planning',
    path: '/planning',
    component: 'layout.base$view.planning',
    meta: {
      title: '机动路线规划',
      order: 6,
      icon: 'mdi:routes'
    }
  },
  {
    name: 'river',
    path: '/river',
    component: 'layout.base$view.river',
    meta: {
      title: '渡河保障方案',
      order: 5,
      icon: 'mdi:ferry'
    }
  },
  {
    name: 'screen',
    path: '/screen',
    component: 'layout.base$view.screen',
    meta: {
      title: '统计大屏',
      order: 1,
      icon: 'mdi:monitor-dashboard'
    }
  }
];
